### ISSUE TITLE
[A11y]: Pagamento de faturas

### ISSUE THREAD

**Issue by juliainvivo** [VivoDesignTeam/acessibilidade-ops#10]
### Jornada

Pagamento de faturas

### Produto

Novo App

### Squad/Frente

Digimon

### Link Figma

https://www.figma.com/design/a0xJN4hSShhtC2ZKD2bepK/Pagamento-de-faturas?node-id=13615-367465&t=Y3X0ssQPxcgHKIRq-1

### Essa é uma alteração ou uma nova Spec?

Nova Spec

### Relator do pedido

Alan Santiago

### Embaixador de acessibilidade

Gabriel Pens

**Comment by isabelleutsch** [comment]
Spec so teve uma atualização de retirada de um card.
