### ISSUE TITLE
OPS | Documentação das Regiões da página

### ISSUE THREAD

**Issue by EllenSGuissoni** [VivoDesignTeam/acessibilidade-ops#104]
### Descrição da tarefa
Fazer uma documentação sobre os novos padrões que serão inseridos na spec.

---

### Links importantes
- https://telefonicacorp.sharepoint.com/:w:/r/sites/DESIGNOPSECAREVIVO.TMBNL-AcessibilidadeOps/_layouts/15/Doc.aspx?sourcedoc=%7Bf2d1f5ea-3996-402e-9e1e-5d460410fe5d%7D&action=editnew 

---

### Etapas da tarefa
- [x] Criar uma documentação sobre o tema 
- [x] Criar uma padronização na lib sobre o tema
- [x] Fazer uma dinâmica com os Embaixadores de A11y com os novos padrões de regiões da pagina nas specs
- [x] Fazer uma pilula sobre o tema 
- [x] Publicar a pílula sobre o tema no teams

**Comment by EllenSGuissoni** [comment]
Foi criado um arquivo no figma para a dinamica com os embaixadores : https://www.figma.com/design/4KcTe40BncprHl5nG5Mii5/%5BESTUDO%5D-Embaixadores-de-A11y?node-id=6306-420&t=cRGVQOuBz5B1KcCl-1

**Comment by EllenSGuissoni** [comment]
a documentação foi passada para o zeroheight do Framework de A11y

**Comment by juliainvivo** [comment]
Agendar data das próximas pírulas com a Dea

**Comment by EllenSGuissoni** [comment]
A pílula será publicada hoje (30/10)
