### ISSUE TITLE
OPS | Estudo dos símbolos

### ISSUE THREAD

**Issue by EllenSGuissoni** [VivoDesignTeam/acessibilidade-ops#106]
### Descrição da tarefa
Com parceria com o time de Content, este estudo visa levantar os comportamentos de cada símbolo: 

---

### Links importantes
- https://www.figma.com/design/UwepXtxOIVUTgMUoPG4IQs/Estudo%3A-uso-de-s%C3%ADmbolos?node-id=78-5889&t=9dwJeDI9j8CJHPd6-1

---

### Etapas da tarefa

@EllenSGuissoni 
- [x] Símbolo de +
- [x] Símbolo de -

@1996-nauta 
- [x] Símbolo de / (substituição de por e data)
- [x] Símbolo de *

@isabelleutsch 
- [x] Símbolo de X (vezes) - vezes ou parcelas?
- [x] Símbolo de X (outros contextos/fora da regra)

@rdghiga 
- [x] Símbolo de ✓ (check)
- [x] Símbolo de =

@Ro-Matos 
- [x] Símbolo de %
- [ ] Tags: -10%; 10%; 10% de desconto; 10% off
- [ ] Símbolo ordinal º e ª

@juliainvivo 
- [x] Símbolo < >
- [x] Símbolo ->

### Etapa do Status da tarefa
- [x] Documentação da WCAG (quais diretrizes da WCAG falam sobre uso de símbolos)
- [x] Revisão de literatura (quais outros canais falam sobre uso de símbolos)
- [x] Documentação do manual de uso NVDA
- [x] Criação de página em HTML para texto de leitura com o leitor de tela (NVDA)
- [x] Benchmark com casos de uso em outros sites (entender como é o contexto e comportamento no uso de símbolos)
- [ ] Indicação de utilização de uso (indicar qual a melhor forma de utilizar o símbolo, indicando a diferenciação de caractere silábico do caractere matemático para correta leitura, se é viável utilização de literal, fatores como escolha da voz do LT e também das configurações de verbosidade que podem impactar na leitura dos símbolos)

**Comment by 1996-nauta** [comment]
Mapeamento dos símbolos realizado V1. Foram mapeados as documentações da WCAG, Literatura em geral, Manual do NVDA. Escolha de verbosidade pelo usuário. 

Na V2. estamos mapeando casos de uso, com prints e indicação de como é feita a leitura pelo LT

**Comment by 1996-nauta** [comment]
[Estudo dos Simbolos](https://everisgroup-my.sharepoint.com/:w:/g/personal/pizidios_emeal_nttdata_com/ET1pKCR9swxDgxCF1Xsp1WIB4OpqzPetygoSIZSyAow0Gg?e=bJcNMh)

**Comment by 1996-nauta** [comment]
**Mapeamentos dos símbolos**
1. Documentação da WCAG (quais diretrizes da WCAG falam sobre uso de símbolos)
2. Revisão de literatura (quais outros canais falam sobre uso de símbolos)
3. Documentação do manual de uso NVDA
4. Criação de página em HTML para texto de leitura com o leitor de tela (NVDA)
5. Benchmark com casos de uso em outros sites (entender como é o contexto e comportamento no uso de símbolos)
6. Indicação de utilização de uso (indicar qual a melhor forma de utilizar o símbolo, indicando a diferenciação de caractere silábico do caractere matemático para correta leitura, se é viável utilização de literal, fatores como escolha da voz do LT e também das configurações de verbosidade que podem impactar na leitura dos símbolos)

**Comment by 1996-nauta** [comment]
@isabelleutsch está mapeando o comportamento de uso do símbolo "X", com o talkback
