### ISSUE TITLE
Pilulas no Framework

### ISSUE THREAD

**Issue by EllenSGuissoni** [VivoDesignTeam/acessibilidade-ops#153]
### Descrição da tarefa
Criar um guia no framework com as pilulas de acessibilidade já criadas

---

### Links importantes
- [Framework de acessibilidade](https://zeroheight.com/4e1de193d/p/752389-o-que-e-o-framework)

---

### Etapas da tarefa
- [x] Criar um guia para as pilulas
- [x] Passar todas as pilulas para o framework
- [x] Publicar essa guia 
- [x] Fazer uma comunicação para a divulgação dessa nova guia

**Comment by juliainvivo** [comment]
Agendar com a Dea a comunicação dessa informação.
