### ISSUE TITLE
[A11y]: SPEC / Revisão - Oferta Fibra PagBank (AGILE)

### ISSUE THREAD

**Issue by ppereisi** [VivoDesignTeam/acessibilidade-ops#154]
### Jornada

Contratação de Fibra Agile - Oferta Pagbank

### Descrição

Revisão de Spec de a11y para adição de um callout com logo + fraseologia dentro do carrinho

### Produto

On Going

### Squad/Frente

Agile - Ongoing

### Link Figma

https://www.figma.com/design/9GB2JrywIFtCMQv5LRku9X/%5BSPECS%5D-Pagbank-%2B-Vivo?node-id=3-7&t=R2LBx4IddIx3YckR-1

### Essa é uma alteração ou uma nova Spec?

Nova Spec

### Relator do pedido

Paulo Pereira

### Embaixador de acessibilidade

No response

**Comment by EllenSGuissoni** [comment]
spec validada e retornada para o PD fazer as correções.
