### ISSUE TITLE
Mensuração Onboarding A11y

### ISSUE THREAD

**Issue by rdghiga** [VivoDesignTeam/acessibilidade-ops#155]
### Descrição da tarefa
Mensurar se o material de onboarding de a11y foi efetivo para os colaboradores

---

### Links importantes
- ...
- ...
- ...

---

### Etapas da tarefa
- [ ] Definir processos
- [ ] ...
- [ ] ...

**Comment by EllenSGuissoni** [comment]
- [ ] Questionários de satisfação
- [ ] Questionários de nivelamento
- [ ] Cronograma macro

**Comment by EllenSGuissoni** [comment]
Link do formulário de conhecimento: https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=h9xIMPBDAEGay64ZcceTlZ0i7XtqEUFFujdT31Nisz9UMUs4U09CMFVNTFNRTENVVjIxOVNRM1hLUy4u&Token=46c6787e907f4c61860dbc8776469f19
