### ISSUE TITLE
[A11y]: Portal - Títulos na página de resultado de busca

### ISSUE THREAD

**Issue by ygorsilvaalcantara** [VivoDesignTeam/acessibilidade-ops#166]
### Jornada

Resultado de Busca no Portal

### Descrição

Anteriormente adicionamos títulos no modal de busca do Portal, negócios agora solicitou para adicionarmos esses mesmos títulos dentro da página de resultado de buscas.

### Produto

Portal

### Squad/Frente

NA/OnGoing

### Link Figma

https://www.figma.com/design/4pjIXVsCSNRCTmWjYBhKCz/%5BHANDOFF%5D-Ajuste-da-Busca-Org%C3%A2nica%2FSugeridas?node-id=425-2481&t=lpBXKQpI4fh2qMAJ-1

### Essa é uma alteração ou uma nova Spec?

Nova Spec

### Relator do pedido

Ygor Alcantara

### Embaixador de acessibilidade

Ygor Alcantara

**Comment by rdghiga** [comment]
Spec ajustada e validada!
