### ISSUE TITLE
[A11y]: Revisão de Spec - SVAs Flexíveis Agile

### ISSUE THREAD

**Issue by ppereisi** [VivoDesignTeam/acessibilidade-ops#173]
### Jornada

Contratação de Vivo Total V + SVAs Flexíveis (AGILE)

### Descrição

Este projeto via implementar a oferta de Streamings junto às Ofertas de Vivo Total. A estratégia foi pensada em Vivo Total pois atualmente os streamings não são ofertados para este produto, gerando uma grande perda de receita. Apenas 4% dos clientes hoje que adquirem Vivo Total compram SVAs apartados e por um preço maior do que se ofertado numa oferta combada.

### Produto

On Going

### Squad/Frente

Agile - Ongoing

### Link Figma

https://www.figma.com/design/TRIBALRQ0ukT038a90LZhA/%5BHANDOFF%5D-SVA-Flex%C3%ADvel----Agile?node-id=4-12172&t=Q96OSYCtlXnLvf7H-1

### Essa é uma alteração ou uma nova Spec?

Nova Spec

### Relator do pedido

Paulo Pereira

### Embaixador de acessibilidade

Ygor Alcantara / Marcelo Azevedo

**Comment by EllenSGuissoni** [comment]
spec validada e liberada
