### ISSUE TITLE
[A11y]: Revisão de Spec - Serviço de auto monitoramento Agile

### ISSUE THREAD

**Issue by ppereisi** [VivoDesignTeam/acessibilidade-ops#174]
### Jornada

Contratação de Fibra 500M + Serviço de auto monitoramento (AGILE)

### Descrição

O objetivo desse projeto é criar um serviço de auto monitoramento com câmeras inteligentes, onde o cliente paga uma mensalidade adicional junto a sua fatura de banda larga e recebe uma câmera inteligente para ver, através do App Vivo Casa Inteligente, o que acontece na sua casa em tempo real. O cliente pode escolher planos que permitam armazenar as gravações dos vídeos dos últimos dias e/ou incluir mais câmeras inteligentes em sua assinatura.

### Produto

On Going

### Squad/Frente

Agile - Ongoing

### Link Figma

https://www.figma.com/design/dHfxuDYstxiLuE7qLXUpbE/%5BHANDOFF%5D-Vivo-Fibra-%2B-Intelbras---Agile?node-id=2-9874&t=6H9BTS5frBP3ZsYe-1

### Essa é uma alteração ou uma nova Spec?

Nova Spec

### Relator do pedido

Paulo Pereira

### Embaixador de acessibilidade

Ygor Alcantara / Marcelo Azevedo

**Comment by EllenSGuissoni** [comment]
spec validada e liberada
