### ISSUE TITLE
[Revisão de Spec]: Menu responsivo - Redesign

### ISSUE THREAD

**Issue by mazevedc** [VivoDesignTeam/acessibilidade-ops#189]
### Jornada

Menu responsivo - Redesign

### Descrição

Ajustes (quick wins) de design e acessibilidade no header e menu do Portal, mobile.

### Produto

On Going

### Squad/Frente

Ongoing

### Link Figma

https://www.figma.com/design/6LzmQcDS3MPq6H9TYsdwfD/%5BESTUDO%5D-Menu-responsivo---Redesign?node-id=118-885&t=ktkIbkWlchHxd6wI-1

### Essa é uma alteração ou uma nova Spec?

Nova Spec

### Relator do pedido

Marcelo Chaves

### Embaixador de acessibilidade

Marcelo Chaves

**Comment by rdghiga** [comment]
Spec validada!
