### ISSUE TITLE
[Revisão de Spec]: Pagamento | Checkout

### ISSUE THREAD

**Issue by ruicauby** [VivoDesignTeam/acessibilidade-ops#213]
### Jornada

Checkout Uniecom

### Descrição

Segunda entrega da jornada de Checkout da Uniecom. Entrega do segundo ciclo.

### Produto

Uniecom

### Squad/Frente

Checkout Uniecom

### Link Figma

https://www.figma.com/design/Qp6EvUN8nADuqfZQ01SzqD/Checkout?node-id=15933-168158

### Essa é uma alteração ou uma nova Spec?

Nova Spec

### Relator do pedido

Rui Cauby

### Embaixador de acessibilidade

Rui Cauby

**Comment by rdghiga** [comment]
Specs ajustadas e validada!
