### ISSUE TITLE
[Revisão de Spec]: Uniecom | Carrinho | Ciclo 2

### ISSUE THREAD

**Issue by jeronymots** [VivoDesignTeam/acessibilidade-ops#218]
### Jornada

Carrinho

### Descrição

A entrega do ciclo 2 se refere ao preenchimento de campo do DDD e escolha de número

### Produto

Uniecom

### Squad/Frente

Carrinho

### Link Figma

https://www.figma.com/design/h5loZBcOxO0OfWksLYb521/Handoff-%7C-Unicom?node-id=1815-140216

### Essa é uma alteração ou uma nova Spec?

Nova Spec

### Relator do pedido

Jeronymo Tomazelli

### Embaixador de acessibilidade

Jessica Leroy

**Comment by EllenSGuissoni** [comment]
Spec validada , e aguardando as alterações serem feitas para fazer a validação novamente

**Comment by EllenSGuissoni** [comment]
spec validada e liberada.
