### ISSUE TITLE
Documentação dos componentes - Display Media Card

### ISSUE THREAD

**Issue by juliainvivo** [VivoDesignTeam/acessibilidade-ops#35]
### Descrição da tarefa

---

### Links importantes
- Ticket no Jira ES:
https://jira.tid.es/browse/OBVIVO-2633

---

### Etapas da tarefa
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by Ro-Matos** [comment]
Por default os componentes de cards (display media card, poster card, etc) são renderizados com o title como H3, e o title é  primeiro elemento lido do card por teoricamente passar o contexto principal. Porém no APP Vivo, em quase todos os casos de uso, o pre-title que passa o contexto principal do card e assim deveria ser lido primeiro.

Para este cenário, Mística disponibilizou a prop _**pretitleAs**_ aonde é possivel definir que o pre-title é um título e assim ele será lido primeiro que o title.

**Pró:** Maior flexibilidade para adequação do componente.
**Contra:** Por não ser a propriedade default será necessário adequação manual em dev para cada caso.

**Comment by Ro-Matos** [comment]
Por default os componentes de cards (display media card, poster card, etc) são renderizados com o title como H3, e o title é primeiro elemento lido do card por teoricamente passar o contexto principal. Porém no APP Vivo, em quase todos os casos de uso, o pre-title que passa o contexto principal do card e assim deveria ser lido primeiro.

Para este cenário, Mística disponibilizou a prop pretitleAs aonde é possivel definir que o pre-title é um título e assim ele será lido primeiro que o title.

Pró: Maior flexibilidade para adequação do componente.
Contra: Por não ser a propriedade default será necessário adequação manual em dev para cada caso.
