### ISSUE TITLE
[Framework] Atualizar com informações do time de A11y

### ISSUE THREAD

**Issue by juliainvivo** [VivoDesignTeam/acessibilidade-ops#47]
Adicionar Equipe OPS e Embaixadores

**Comment by EllenSGuissoni** [comment]
a documentação foi feita. 

QUEM SOMOS E EMBAIXADORES : https://designopsvivo.zeroheight.com/styleguide/s/105844/p/576bb3-quem-somos
LINKS IMPORTANTES: https://designopsvivo.zeroheight.com/styleguide/s/105844/p/763bc0-links-importantes
