### ISSUE TITLE
Referências de especificações a11y

### ISSUE THREAD

**Issue by rdghiga** [VivoDesignTeam/acessibilidade-ops#63]
### Descrição da tarefa
Exemplos de especificações de a11y para cada componente.

✅ Input autocomplete
✅ Fab button
✅ Campos preenchidos / Variáveis
- [x] Callout
- [x] Carregando
- [x] Skeleton
- [x] Botão voltar
- [x] Botão fechar
- [x] Multiselect
- [x] Toggle
- [x] Tab
- [x] PDF
- [x] Carrossel
- [x] Lista ordenada
- [x] Tabelas
- [x] Título da Interface
- [x] OTP
- [x] Breadcrumb
- [x] Checkbox
- [x] Feedback de senha
- [x] Lista ordenada
- [x] Rating
- [x] Regiões da página
- [x] Sanckbar

---

### Links importantes
- [Arquivo do Figma](https://www.figma.com/design/9VdgeX7r0bOm8KiWbvWQr8/Master-%7C-Refer%C3%AAncias-de-especifica%C3%A7%C3%A3o-a11y?node-id=3-102&t=wpGWztH32aXVPvow-1)

**Comment by juliainvivo** [comment]
Unificar com #54
