### ISSUE TITLE
[A11y]: Splash Screen

### ISSUE THREAD

**Issue by juliainvivo** [VivoDesignTeam/acessibilidade-ops#64]
### Jornada

Splash Screen

### Descrição

Precisamos realizar a criação da Spec de Acessibilidade para o componente Splash Screen

### Produto

Novo App

### Squad/Frente

Ops

### Link Figma

https://www.figma.com/design/Via0lhrPKYB6DOQMbWcshO/Loading-animation?node-id=1-3

### Essa é uma alteração ou uma nova Spec?

Nova Spec

### Relator do pedido

Júlia Alberto

### Embaixador de acessibilidade

Júlia Alberto

**Comment by Ro-Matos** [comment]
Após investigar, já existe uma documentação do Mística para o Loading Screen e BrandLoading Screen. Foi indicado a equipe, aguardando verificarem.
https://www.figma.com/design/KYdCKU8obcDapI8ihpsaWs/%F0%9F%94%B8-LoadingScreen-Specs?node-id=205-1654&t=KSZBQzzpgtMfMapH-4

**Comment by Ro-Matos** [comment]
Foi criada a spec da tela no APP Vivo.
E indicado a spec do componente. Aparentemente não temos mais ações.

Ticket: https://jira.tid.es/browse/OBVIVO-2424
