### ISSUE TITLE
[A11y]: Assinaturas - Detalhe de Consumo

### ISSUE THREAD

**Issue by juliainvivo** [VivoDesignTeam/acessibilidade-ops#89]
### Jornada

Assinaturas - Detalhe de Consumo

### Produto

Novo App

### Squad/Frente

Digimon

### Link Figma

https://www.figma.com/design/srp4LxyWqsM1Nk8BaTO3jd/Assinaturas?m=auto&node-id=27348-80508&t=bgkJOLjMFvs6zkf5-1

### Essa é uma alteração ou uma nova Spec?

None

### Relator do pedido

Alan Santiago

### Embaixador de acessibilidade

Gabriel Pens

**Comment by isabelleutsch** [comment]
Atualização de um spec já existente. 

Spec bem antiga.
