### ISSUE TITLE
[A11y]: Troca de Assinatura Banda Larga com Alta Móvel

### ISSUE THREAD

**Issue by juliainvivo** [VivoDesignTeam/acessibilidade-ops#9]
### Jornada

Troca de Assinatura Banda Larga com Alta Móvel

### Produto

Novo App

### Squad/Frente

Cavaleiros do Zodíaco

### Link Figma

https://www.figma.com/design/IEVY1TCFUuTLtWHMfZqgaG/Troca-de-Plano-fixa-%7C-Novo-App?node-id=10708-209268&t=f17qfpbAVXxDycv4-1

### Essa é uma alteração ou uma nova Spec?

Nova Spec

### Relator do pedido

Rodrigo Moreira Santos

### Embaixador de acessibilidade

Bruna Monise Paulino

link novo

https://www.figma.com/design/1nO0V47QiIHPX5dOdAezic/Troca-de-assinatura-fixa---Novo-App?node-id=2838-69543&node-type=section&t=dKnELAsQF9E6JCPT-0

**Comment by isabelleutsch** [comment]
Mudança de arquivo feita pela Bruna[
](https://www.figma.com/design/1nO0V47QiIHPX5dOdAezic/Troca-de-assinatura-fixa---Novo-App?node-id=2838-69543&node-type=section&t=dKnELAsQF9E6JCPT-0)
